### ISSUE TITLE
Wrong algo dvbcsa

### ISSUE THREAD

**Issue by hemmingway-1** [oscam-emu/oscam-patched-old#100]
I tried since some days to get oscam running on fedora 37 in a virtual machine.
I can compile anything, but the screen on my pc is only black.
The former installation works fine several years.
Now only the cygwin binary works fine, 
In the dvbviewer logfile I found a big difference:
cygwin binary (working): 
DVBAPI Command: CaSetDescrMode
(dvbapiclient) Adapter: 2, index: 0, algo: DvbAltCsa, mode: Cbc
Fedora compilation (not working):
DVBAPI Command: CaSetDescrMode
(dvbapiclient) Adapter: 2, index: 0, algo: DvbCsa, mode: Cbc

My question: How I can change the algo?

Greetings Bernhard

**Comment by nautilus7** [comment]
Can you post a debug log with a recent build? And describe what is not working...
