### ISSUE TITLE
Windows Oscam-emu patch İcam

### ISSUE THREAD

**Issue by Serpil34** [oscam-emu/oscam-patched-old#106]
After the latest OSCam-emu patch, Windows IP does not appear. I would be very happy if you could help me with this.

14:57:17 00000000 s >> OSCam << cardserver log switched, version 1.20_svn, build r11726-798 (x86_64-pc-cygwin-ssl-libusb-pcsc)
14:57:17 00000000 s     (main) System name    = CYGWIN_NT-10.0-22631
14:57:17 00000000 s     (main) Host name      = Ptersburg_34
14:57:17 00000000 s     (main) Release        = 3.4.9-1.x86_64
14:57:17 00000000 s     (main) Version        = 2023-09-06 11:19 UTC
14:57:17 00000000 s     (main) Machine        = x86_64
14:57:17 00000000 s     (main) creating pidfile /cygdrive/c/Users/SSK_3/AppData/Local/Temp/_oscam/oscam.pid with pid 1989
14:57:17 00000000 s      (emu) OSCam-Emu version 798
14:57:17 00000000 s     (main) signal handling initialized
14:57:17 5851F42D h    (webif) webif: decompressed 179101 bytes back into 478800 bytes
14:57:17 00000000 s   (reader) emulator [emu] creating thread for device emulator
14:57:17 2AD7E0E5 r      (emu) Stream key delayer initialized
14:57:17 00000000        (emu) INFO: FFDecsa parallel mode = 128
14:57:17 2AD7E0E5 r      (emu) Stream relay server initialized
14:57:17 2AD7E0E5 r   (reader) emulator [emu] Reader initialized (device=emulator, detect=cd, mhz=357, cardmhz=357)
14:57:17 00000000 s     (main) waiting for local card init
14:57:17 5851F42D h    (webif) HTTP Server running. ip=0.0.0.0 port=8888
14:57:22 00000000 s     (main) init for all local cards done
14:57:22 00000000 s (emmcache) loading emmcache disabled since no reader is using it!
14:57:22 00000000 s (emmcache) loading emmstats disabled since no reader is using it!
14:57:22 00000000 s (anticasc) anti cascading disabled
14:57:22 00000000 s     (gbox) local gbox failed init

**Comment by WXbet** [comment]
Please try it again with oscam-emu 800.
