### ISSUE TITLE
Feature CAID mapping for non dvbapi client

### ISSUE THREAD

**Issue by Saentist** [oscam-emu/oscam-patched-old#77]
Currently if DVBAPI used user can type in `oscam.dvbapi`
```M: AAAA BBBB```
and can use card with CAID **AAAA** for services with CAID **BBBB**
https://wiki.streamboard.tv/wiki/OSCam/en/Config/oscam.dvbapi

But in this case clients of NewCam or CCCam etc, cannot use this feature.
It can be used only by local dvbapi descrambling, not even network dvbapi
Is here a way this option to be implemented?

**Comment by caveman99** [comment]
This is in OSCAM trunk scope, and not in the EMU domain. This is for EMU development only.

Off topic: The betatunnel feature should provide a similar mechanism to you for remote clients.

**Comment by Saentist** [comment]
Whatever I try with betatunnel not work for CAID 4Axx and 55xx
in same time with dvbapi work

**Comment by nautilus7** [comment]
Your client, which I suppose use dvbapi, should set the caid mapping. Not the server.
