### ISSUE TITLE
New Feature Request for Director/Tandberg Key Detection in SoftCam.Key

### ISSUE THREAD

**Issue by LarryS188** [oscam-emu/oscam-patched-old#82]
Currently the only field that Director/Tandberg uses to find the key from SoftCam.Key is the entitlement number.  This is causing a conflict because I have several channels that use 0001 or 0002 with different keys.  

Has anyone considered adding the option for additional filtering similar to PowerVu or Biss.  There is a unique EcmPid for each of these channels that would be one option.

I am looking for a method that would allow me to have all the keys in SoftCam.Key and have the key selection be filtered to select the correct key based on the channel I am trying to watch,

**Comment by nautilus7** [comment]
Is this request valid today? How many channels use the same key nowadays?
