### ISSUE TITLE
44A0 56E

### ISSUE THREAD

**Issue by EnoSat** [oscam-emu/oscam-patched-old#99]
fixed patch for RuskijMir from 56 East ?
[oscam-ymodv1859-rm56e.zip](https://github.com/oscam-emu/oscam-patched/files/10717261/oscam-ymodv1859-rm56e.zip)
![photo1676284744](https://user-images.githubusercontent.com/4271667/218442842-bd53cf16-73e5-440c-a946-a7accfe03cc4.jpeg)
[OSCam-11718-798 (armv7ve libusb) test44A0.zip](https://github.com/oscam-emu/oscam-patched/files/10785837/OSCam-11718-798.armv7ve.libusb.test44A0.zip)

**Comment by nealchenjob** [comment]
did you have algo for RuskiyMir(caid: 0x44A)? is it possible to share the source code. thanks.
